site_name: iCal4j User Guide
site_url: https://ical4j.github.io/ical4j-user-guide/
theme:
  name: material
  favicon: images/favicon.png
  logo: images/logo-48.png
repo_url: https://github.com/ical4j/ical4j
repo_name: ical4j/ical4j
google_analytics:
  - UA-402774-10
  - auto
extra:
  disqus: ical4j
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/benfortuna
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/benfortuna
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/micronode
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Android: android.md
  - Compatibility: compatibility.md
  - RFC Compliance: compliance.md
  - Connector: connector.md
  - CUAs: cuas.md
  - Date/Time Concepts: datetime.md
  - Encoding: encoding.md
  - Examples: examples.md
  - Extensions: extensions.md
  - External Resources: external-resources.md
  - FAQ: faq.md
  - Filtering: filtering.md
  - Groovy: groovy.md
  - Indexing: indexing.md
  - Integration: integration.md
  - Maven: maven.md
  - Parsing: parser.md
  - Projects using iCal4j: projects.md
  - Recurrences: recurrences.md
  - Resources: resources.md
  - Roadmap: roadmap.md
  - Timezones: timezones.md
  - vCard: vcard.md
  - ZoneInfo Outlook: zoneinfo-outlook.md